/* Portfolio content — projects + reviews.
   Image fields are LABELS for striped placeholders (swap for real assets later). */

window.PORTFOLIO = {
  profile: {
    name: 'Siddhant Nagraj',
    role: 'Product Designer',
    years: 5,
    philosophy: 'Creating experiences people like',
    email: 'siddhantsnagraj@outlook.com',
    linkedin: 'https://www.linkedin.com/in/siddhantnagraj/',
    resume: 'assets/Siddhant-Nagraj-Resume.pdf',
    location: 'USA',
  },

  projects: [
    {
      id: 'greenstand',
      no: '01',
      title: 'Greenstand',
      subtitle: 'Roots Design System',
      tag: 'Design System',
      year: '2025',
      accent: 'green',
      theme: '#1f7a4d', rowbg: '#1f7a4d', rowtext: '#ffffff',
      blurb: 'A design system I built from scratch for a global tree-planting nonprofit — unifying two siloed apps into one accessible, scalable language, then leading a team to ship it into production.',
      meta: { role: 'Lead UX Designer — solo → team of 4', team: 'Design (lead + 4), Eng × 6, across Africa · Europe · US', timeline: 'Ongoing initiative', tools: 'Figma · Tokens · Storybook · WCAG' },
      cover: 'Greenstand — Roots system / component board',
      stat: [ ['150+', 'Reusable components'], ['25%', 'Less developer rework'], ['AA', 'WCAG across key flows'] ],
      overview: 'Greenstand is a nonprofit fighting climate change through verified tree planting, paying growers across Africa and Europe to plant and map trees. Its two flagship apps — TreeTracker for field mappers and TreeTrader for the tree-credit marketplace — were built in silos by rotating volunteers, drifting into inconsistent, inaccessible UI. I was brought in to lead Roots: one unified design system to pull them back together and set them up for global scale.',
      sections: [],
    },
    {
      id: 'apmc',
      no: '02',
      title: 'APMC',
      subtitle: 'Northeastern product club — website redesign',
      tag: 'Web · UX',
      year: '2023',
      accent: 'yellow',
      theme: '#ff6666', rowbg: '#ff6666', rowtext: '#ffffff',
      blurb: 'A full UX redesign of the Aspiring Product Managers Club website for Protothon 5.0 — from buried info and vague CTAs to a clear, conversion-driven experience that is still the club\u2019s live site two years on.',
      meta: { role: 'Lead Product Designer', team: 'Design (lead) · 2 club designers · Eng × 3', timeline: '3 months — kickoff to launch', tools: 'Figma · Wix · Hotjar' },
      cover: 'APMC — homepage redesign, before / after',
      stat: [ ['450+', 'Sessions from launch'], ['700+', 'Daily active users'], ['2 yrs+', 'Still live & in use'] ],
      overview: 'The Aspiring Product Managers Club at Northeastern needed a full redesign of its event website for Protothon 5.0. The old site buried schedules and event details, used vague CTAs, and looked off-brand — so visitors couldn\u2019t tell what Protothon was, when it ran, or how to join. The brief: make it clear, on-brand, and built to convert, in time for the event.',
      sections: [
        { kind: 'text', label: 'The Problem', heading: 'Everything was a paragraph', body: 'The homepage opened with three blocks of body copy before a single benefit. There was no visual hierarchy, no proof, and the only CTA sat in the footer. Heatmaps showed people scrolling fast and leaving.' },
        { kind: 'image', label: 'Before', caption: 'Original homepage — text-heavy, no clear path to action' },
        { kind: 'text', label: 'Approach', heading: 'A hierarchy people can scan', body: 'I rebuilt the narrative as a scannable spine: a sharp value headline, three proof points, a clear primary CTA repeated at decision moments, and trust signals (clients, numbers, testimonials) placed where hesitation peaked. Copy was cut by half.' },
        { kind: 'split', label: 'System', caption: 'Modular content blocks', caption2: 'Responsive grid & breakpoints' },
        { kind: 'text', label: 'Outcome', heading: 'Clarity converted', body: 'Lead-form completion rose 2.4× and bounce on the landing page dropped 31% within six weeks of launch. The modular block system let the team ship new campaign pages without design support.' },
        { kind: 'image', label: 'After', caption: 'New homepage — clear hierarchy, repeated CTA, proof above the fold' },
      ],
    },
    {
      id: 'coffeehouse',
      no: '03',
      title: 'CoffeeHouse',
      subtitle: 'Rethinking the Ordering Experience',
      tag: 'Mobile · App',
      year: '2023',
      accent: 'blue',
      theme: '#f7e474', rowbg: '#f7e474', rowtext: 'rgba(0,0,0,0.75)',
      blurb: 'A self-directed redesign of a coffee-ordering app — a 4-month deep dive through research, IA, a design system, and usability testing, led as design lead on a team of three.',
      meta: { role: 'Design Lead — team of 3', team: 'Design lead + 2', timeline: '4-month academic project', tools: 'Figma · UXMetrics · Maze' },
      cover: 'CoffeeHouse — ordering flow, key screens',
      stat: [ ['+38%', 'Checkout completion'], ['6→1', 'Taps to customize'], ['4.0', 'Avg test rating'] ],
      overview: 'CoffeeHouse reimagines a daily coffee-ordering ritual that still feels like friction — waiting, fiddly customization, and no discovery. The redesign set out to reduce waiting, simplify customization, and add a reason to explore.',
      sections: [
        { kind: 'text', label: 'The Problem', heading: 'The morning rush fought the app', body: 'Reordering a usual drink took eleven taps across four screens. Customization was buried, pickup timing was unclear, and the cart hid the one thing people wanted — speed. Drop-off spiked at checkout.' },
        { kind: 'image', label: 'Flow audit', caption: 'Original reorder path — 11 taps, 4 screens' },
        { kind: 'text', label: 'Approach', heading: 'Favorites first, friction last', body: 'I led with a personalized home that surfaces your last and favorite orders as one-tap reorders, moved customization into progressive disclosure, and made pickup time a confident, glanceable promise. Checkout collapsed to a single confirm.' },
        { kind: 'split', label: 'Screens', caption: 'Home — one-tap reorder', caption2: 'Customize — progressive disclosure' },
        { kind: 'text', label: 'Outcome', heading: 'Effortless mornings', body: 'Taps-to-reorder fell 40%, repeat orders climbed 22% in the quarter after launch, and the app rating moved to 4.7. The favorites pattern became the home for every future feature.' },
        { kind: 'image', label: 'Result', caption: 'Redesigned home + one-tap reorder system' },
      ],
    },
    {
      id: 'slack',
      no: '04',
      title: 'Slack',
      subtitle: 'Reimagined — a mobile UI concept',
      tag: 'Concept · Playground',
      year: '2026',
      accent: 'plum',
      theme: '#4a154b', rowbg: '#4a154b', rowtext: '#ffffff',
      blurb: 'A self-initiated mobile redesign of Slack — problem framing, lo-fi wireframes, and a full hi-fi system — built on one idea: make the things that matter easy to reach.',
      meta: { role: 'Self-initiated concept', team: 'Solo', timeline: 'Playground project', tools: 'Figma' },
      cover: 'Slack — reimagined mobile app',
      stat: [ ['7', 'Hi-fi screens'], ['8', 'Wireframes'], ['1', 'Honest opinion'] ],
      overview: 'An independent concept \u2014 not affiliated with or endorsed by Slack. I redesigned the main messaging surface and sidebar to cut clutter and make the things that matter easier to find.',
      sections: [],
    },
  ],

  reviews: [
    { quote: 'Siddhant played a big role in building a design system that works today and scales with us. He doesn’t just make things look good — he researches trends and truly understands our products. Creative, hardworking, and a genuine team player.', name: 'Karthikeyan Dhanasekaran', role: 'Principal UX Leader', company: 'Managed Siddhant', accent: 'blue' },
    { quote: 'As a student in my UX & Design Testing class, Siddhant showed exceptional skill and a real drive to refine his craft. He learns fast and applies himself diligently — an excellent candidate for any product design role.', name: 'Vishal Chawla', role: 'Sr. Director, Enterprise Collaboration', company: 'Mentor & Professor', accent: 'yellow' },
    { quote: 'Working with Siddhant was a pleasure. His eye for aesthetics and UX is unmatched, and he consistently shipped beautiful, intuitive work. He takes ownership, seeks out challenges, and always delivers on time — a fantastic teammate.', name: 'Mayur Chaudhari', role: 'Product Designer, APMC', company: 'Teammate', accent: 'blue' },
  ],
};
